### ISSUE TITLE
Rename to Open Seattle

### ISSUE THREAD

**Issue by sethvincent** [openseattle/discuss#1]
On July 2, we'll rename Code for Seattle to Open Seattle. The goal: create a more diverse membership.

### Tasks included in renaming:

- [x] logo: ideally will work as horizontal rectangle & as hexagon with point at top. (#10) 
- [x] mission statement ([proposed](https://github.com/openseattle/discuss/issues/1#issuecomment-118339080))
- [ ] styleguide (#14)
- [x] try to get twitter.com/openseattle, but we definitely have twitter.com/open_seattle
- [x] switch to github.com/openseattle
- [x] create github.com/openseattle/openseattle.github.io
- [x] set up dns for openseattle.org
- [x] invite everybody to openseattle.slack.com (use this: https://openseattleslack.herokuapp.com)
- [x] mailchimp: rename codeforseattle account to openseattle
- [x] write a blog post that explains the changes and describes upcoming events.
- [x] press release. let's tell everybody about it. it can mostly have the same content as the blog post.
- [x] plan july events (#12)

On July 2 we'll split up these tasks among the group, so we'll need to have all login information on hand.

**Comment by LukeSwart** [comment]
As we discussed today, "Open Seattle" is a little too... open. To attract the right crowd I came up with the following names:

 * rethink Seattle
 * Shake up Seattle
 * Seattle shakers
 * Seatown shakers
 * Seatown pushers

Just throwing these out there, we'll see what sticks :-) 

But I think those names reflect the mission statement a little better than "Open Seattle". Wait, do we have a mission statement? Perhaps it would be something like **We are "movers and shakers" with diverse talents working together to improve the communities of Seattle through innovative technology, art, storytelling, and design.**

Maybe we should think up a new mission statement before a new name...

**Comment by loganfranken** [comment]
Hey there!

Sorry I wasn't there for the discussion, but I would love to hear why "Open Seattle" was determined to be too broad of a name?

It seems like a wonderful name to me: "open" has technical connotations but also feels inclusive enough for non-technical folks as well.

Either way, I think @LukeSwart's suggestion to come up with a mission statement first seems like a great idea. Are there any existing materials to cull a mission statement from?

**Comment by LukeSwart** [comment]
Hi @loganfranken! Thanks for the input. Seth and I were talking during DiscoTech and "Open Seattle" seems a little ambiguous. For example, if someone wants to start selling Seattle-themed mugs and T-shirts, I don't think Open Seattle would be the right meetup to launch that idea. Perhaps a mission statement can help with that.

You have a good point - "Open Seattle" is a fitting, inclusive, name. It's nice to hear that you support it! I don't think anyone "determined" the name to be too broad, it was just a concern. 

I suppose the "movers and shakers" theme sounds a little pushy, and I definitely don't want to exclude anyone who doesn't think of themselves a "mover" or "shaker" :-)

**Comment by sethvincent** [comment]
:+1: :100: on creating a mission statement.

I added a checklist to the issue for all the things that will need to happen as part of the renaming.

Please suggest things that I've missed.

**Comment by loganfranken** [comment]
Thanks for the info, @LukeSwart! And thanks for putting together the list, @sethvincent!

For the mission statement, should we start from scratch? Or is there anything existing you all had in mind to pull from?

**Comment by loganfranken** [comment]
The current "Who we are" from the website:

> We welcome anyone who is interested in using technology to make civic improvements. Artists, writers, entrepreneurs, leaders, creative thinkers, and coders are invited to civic hacking nights and other events hosted by Code for Seattle.

And the "What we do":

> Code for Seattle runs a weekly civic hacking night, as well as hackathons and other events focused on building the civic technology community in Seattle and building prototype solutions for local civic issues.

Based on all that, @LukeSwart's proposed mission statement seems to fit the bill:

> We are "movers and shakers" with diverse talents working together to improve the communities of Seattle through innovative technology, art, storytelling, and design.

Only change I would suggest is swapping "movers and shakers" with something less colloquial:

> We are a collective with diverse talents working together to improve the communities of Seattle through innovative technology, art, storytelling, and design.

Or more specifically:

> We are a collective of engaged citizens with diverse talents working together to improve the communities of Seattle through innovative technology, art, storytelling, and design.

**Comment by sethvincent** [comment]
:+1:

**Comment by sethvincent** [comment]
here's a google doc with a more detailed plan for doing the renaming this evening: https://docs.google.com/document/d/1RJqQlOHrXXqrNcqm0iDSkv0oEZ0arwDF52yRcZkWG1Q/edit

**Comment by sethvincent** [comment]
http://openseattle.org now works. :tada: 

I also discovered that if I push a commit to a repo then the url for the repo will finally update from codeforseattle/repo to openseattle/repo. Though redirects still don't work, just the link in the repository list at http://github.com/openseattle

**Comment by LukeSwart** [comment]
Here is our proposed statement from last night's meeting:

We are a multi-disciplinary group working together to improve our communities through civic technology. All minds are welcome!

It's also on the doc, and we should eventually add it to the site as well. At some point, it'd be nice to have an 8-10 word statement along with an elaborated description of the group, perhaps with a list of bulleted points on "*you should join Open Seattle if...*"
