### ISSUE TITLE
Design for Seattle

### ISSUE THREAD

**Issue by sethvincent** [openseattle/discuss#17]
Let's hold a design-focused event!

I imagine it being 11 a.m. to 5 p.m. on a Saturday for roughly 50 people. It'll be a design jam rather than a hackathon.

## Potential projects & activities:

- a logo for Seattle NodeSchool
- creating icons for Seattle landmarks, neighborhoods, etc. in the style of the noun project
- conducting user testing sessions for Open Seattle projects
- _suggest more projects & activities!_

## Todos:

- [ ] decide on date
- [ ] get a location
- [ ] food & drinks
- [ ] send invites to area designers & design companies/organizations
- [ ] sponsors
- [ ] _other stuff i'm forgetting right now that we'll add_
